name: build-snapcraft

permissions:
  contents: write

on:
  push:
    paths:
      - "VERSION"
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-snapcraft:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Copy Snapcraft files to source
      run: |
        cp -r dist/snapcraft/* src/

    - name: Fix permissions
      run: |
        chmod -R a+rX src

    - name: List contents of src
      run: |
        ls -l src
        ls -l src/snapcraft.yaml || echo "snapcraft.yaml not found"

    - name: Snapcraft
      uses: snapcore/action-build@v1
      with:
        path: src

    - name: Prepare artifacts
      run: |
        mkdir -p out
        mv src/*.snap out/

    - name: Upload .snap artifacts
      uses: actions/upload-artifact@v6
      with:
        name: build-snapcraft
        path: out/*.snap
        if-no-files-found: error
        compression-level: 9

    - name: Get version tag
      run: |
        VERSION=$(cat VERSION)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Generate checksums
      run: |
        cd out
        for snap in *.snap; do
          hash=$(sha256sum "$snap" | cut -d ' ' -f1)
          name=$(basename "$snap")
          echo "CHECKSUM_SNAP=$hash" >> $GITHUB_ENV
          echo "SNAP_NAME=$name" >> $GITHUB_ENV
        done

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: out/*.snap
        tag_name: ${{ env.VERSION }}
        make_latest: true
        append_body: true
        body: |
          **Linux (Snap):**
          `sha256(${{ env.SNAP_NAME }})  ${{ env.CHECKSUM_SNAP }}`
